#!/usr/bin/env bash
# Install claude-cursor-python-toolkit into a project's .claude/ directory.
#
# Source: .claude/{rules,agents,skills}/cpt/ in this repo (generated by sync-claude.sh).
# Existing cpt/ folders in the target are replaced.
#
# Usage:
#   ./install-claude.sh [target-dir] [--copy]
#
# Examples:
#   ./install-claude.sh                    # symlink into ./.claude
#   ./install-claude.sh /path/to/workspace
#   ./install-claude.sh . --copy             # copy files (no symlink dependency)

set -euo pipefail

TOOLKIT_DIR="$(cd "$(dirname "$0")" && pwd)"
TARGET="."
MODE="symlink"

for arg in "$@"; do
  case "$arg" in
    --copy) MODE="copy" ;;
    -h|--help)
      sed -n '2,13p' "$0"
      exit 0
      ;;
    *)
      if [[ "$arg" != --* ]]; then
        TARGET="$arg"
      fi
      ;;
  esac
done

TARGET="$(cd "$TARGET" && pwd)"
CLAUDE_SRC="${TOOLKIT_DIR}/.claude"
CLAUDE_DEST="${TARGET}/.claude"

install_cpt() {
  local category="$1"
  local src="${CLAUDE_SRC}/${category}/cpt"
  local dest="${CLAUDE_DEST}/${category}/cpt"

  [[ -d "$src" ]] || return 0

  if [[ -e "$dest" || -L "$dest" ]]; then
    echo "  replacing ${dest}"
    rm -rf "$dest"
  fi

  mkdir -p "${CLAUDE_DEST}/${category}"

  if [[ "$MODE" == "copy" ]]; then
    cp -a "$src" "$dest"
  else
    ln -sf "$src" "$dest"
  fi
}

echo "Installing claude-cursor-python-toolkit (Claude Code)"
echo "  toolkit: ${TOOLKIT_DIR}"
echo "  target:  ${CLAUDE_DEST}"
echo "  mode:    ${MODE}"

for category in rules agents skills; do
  install_cpt "$category"
done

echo "Done. Open ${TARGET} in Claude Code to use the rules, skills, and agents."
